In [13]:
import torch

In [3]:
x=torch.randn(3,requires_grad=True)

In [9]:
print(x)
y=x+x+2
print(y)
z=y*y*2
z=z.mean()
print(z)
# z.backward()
print(x.grad)

tensor([1.5412, 0.5652, 0.1800], requires_grad=True)
tensor([5.0823, 3.1303, 2.3599], grad_fn=<AddBackward0>)
tensor(27.4657, grad_fn=<MeanBackward0>)
tensor([4.7216, 3.4202, 2.9066])


In [12]:
# x.requires_grad_(False)
# y=x.detach()
with torch.no_grad():
    y=x+2
    
print(y)

tensor([3.5412, 2.5652, 2.1800])


In [17]:
weights=torch.ones(4,requires_grad=True)

for epoch in range(2):
    model=(weights*3).sum()
    print(model)
    model.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
