Tensor - Basics

In [1]:
import torch

In [3]:
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[ 0.0951, -0.3581, -0.0455,  1.0454],
        [ 0.0747, -0.4868,  1.7716, -0.2079],
        [ 0.5526,  1.0562,  0.3475, -0.7907]])

In [9]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
l=[1,2,3,4]
t=torch.tensor(l)

In [13]:
t
t.dtype
tensor_3d.dtype

torch.float32

Tensor Operations - Reshape and Slice

In [24]:
tor=torch.arange(8)
tor

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [26]:
tor=tor.reshape(2,2,2)
tor

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [32]:
tor2=torch.arange(15)
tor2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
tor2=tor2.reshape(-1,5)
tor2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [39]:
tor3=torch.arange(10)
tor3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
tor3=tor3.view(-1,2)
tor3

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [43]:
tor4=torch.arange(10)
tor4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
tor5=tor4.reshape(-1,2)
tor5

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [46]:
tor4[1]=132
tor4

tensor([  0, 132,   2,   3,   4,   5,   6,   7,   8,   9])

In [47]:
tor5

tensor([[  0, 132],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9]])

In [51]:
#slicing
tor7=tor3.reshape(5,2)
tor7

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [55]:
tor7[4,1]

tensor(9)

In [63]:
tor7[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

Tensor - Math Operations

In [92]:
tor1=torch.tensor([1,2,3,4,5])
tor2=torch.tensor([6,7,8,9,0])

In [67]:
#addition
tor1+tor2

tensor([ 7,  9, 11, 13,  5])

In [68]:
#add longhand
torch.add(tor1,tor2)

tensor([ 7,  9, 11, 13,  5])

In [69]:
#subtraction
tor1-tor2

tensor([-5, -5, -5, -5,  5])

In [71]:
#sub function
torch.sub(tor2,tor1)

tensor([ 5,  5,  5,  5, -5])

In [72]:
#multiplication
tor1*tor2

tensor([ 6, 14, 24, 36,  0])

In [73]:
#mul function
torch.mul(tor1,tor2)

tensor([ 6, 14, 24, 36,  0])

In [75]:
#division
tor2/tor1

tensor([6.0000, 3.5000, 2.6667, 2.2500, 0.0000])

In [76]:
#div function
torch.div(tor2,tor1)

tensor([6.0000, 3.5000, 2.6667, 2.2500, 0.0000])

In [78]:
#modulus
tor2%tor1

tensor([0, 1, 2, 1, 0])

In [80]:
#mod function
torch.remainder(tor2,tor1)

tensor([0, 1, 2, 1, 0])

In [81]:
#exponents
torch.pow(tor1,tor2)

tensor([     1,    128,   6561, 262144,      1])

In [83]:
tor1.add(tor2)

tensor([ 7,  9, 11, 13,  5])

In [94]:
#reassignment
#tor1=tor1+tor2
tor1.add_(tor2)

tensor([ 7,  9, 11, 13,  5])

In [95]:
tor1

tensor([ 7,  9, 11, 13,  5])